/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Analyses
         * @description Recent analyses, filtered.
         *
         *     Both filters are optional and compose:
         *       decision=REVIEW              -> only REVIEW rows
         *       unattached=true              -> only rows with borrower_id IS NULL
         *       decision=REVIEW&unattached=true -> the queue view used by Under review /
         *                                         Declined tabs on the frontend
         */
        get: operations["list_analyses_api_analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}/oversight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit Oversight
         * @description EU AI Act Article 14: the officer decides what the model's output
         *     counts for, not what it says. This endpoint records that decision as
         *     metadata layered over the analysis — the scorecard's decision + score
         *     remain byte-identical to what compute/score produced.
         *
         *     One-shot per analysis for the demo. TODO: post-demo, move to an
         *     append-only oversight_events table so the full review history is
         *     queryable (multiple officers, second reviews, appeals, etc.).
         */
        post: operations["submit_oversight_api_analyses__analysis_id__oversight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/borrowers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Borrowers
         * @description List borrowers with rollup counts + latest verdict. Two subqueries for
         *     the counts, one per-borrower lookup for the latest analysis — good enough
         *     for demo/dev volumes; we can move to a single windowed query when this
         *     starts to matter.
         */
        get: operations["list_borrowers_api_borrowers_get"];
        put?: never;
        /** Create Borrower */
        post: operations["create_borrower_api_borrowers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/borrowers/{borrower_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Borrower */
        get: operations["get_borrower_api_borrowers__borrower_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/borrowers/{borrower_id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Borrower Files */
        post: operations["upload_borrower_files_api_borrowers__borrower_id__files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/borrowers/{borrower_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Borrower */
        post: operations["analyze_borrower_api_borrowers__borrower_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Company */
            company: string;
            /** Loan Request */
            loan_request?: number | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVE" | "REVIEW" | "DECLINE";
            /** Score */
            score: number;
            /** Financials */
            financials: {
                [key: string]: unknown;
            };
            ratios: components["schemas"]["Ratios"];
            /** Flags */
            flags: components["schemas"]["Flag"][];
            /** Factors */
            factors: components["schemas"]["Factor"][];
            /** Counterfactual */
            counterfactual?: string | null;
            /** Memo */
            memo: string;
            /** Officer Action */
            officer_action?: ("CONFIRMED" | "OVERRIDDEN") | null;
            /** Officer Note */
            officer_note?: string | null;
            /** Officer Action At */
            officer_action_at?: string | null;
        };
        /**
         * AnalysisSummary
         * @description Lightweight row for the history list.
         */
        AnalysisSummary: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Company */
            company: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVE" | "REVIEW" | "DECLINE";
            /** Score */
            score: number;
        };
        /**
         * BorrowerAnalyzeRequest
         * @description POST /api/borrowers/{id}/analyze body: which stored files to feed into
         *     the pipeline. All file_ids must belong to this borrower.
         */
        BorrowerAnalyzeRequest: {
            /** File Ids */
            file_ids: string[];
        };
        /**
         * BorrowerCreate
         * @description POST /api/borrowers body.
         */
        BorrowerCreate: {
            /** Name */
            name: string;
            /** Sector */
            sector?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /**
         * BorrowerDetail
         * @description Full borrower page: everything the UI needs to render the profile,
         *     the uploaded files list, and the history of analyses.
         */
        BorrowerDetail: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Sector */
            sector?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Files */
            files: components["schemas"]["FileSummary"][];
            /** Analyses */
            analyses: components["schemas"]["AnalysisSummary"][];
        };
        /**
         * BorrowerSummary
         * @description Row on the borrower list. Rollups let the UI render 'N files · N
         *     analyses · latest DECLINE 42/100' without needing a second fetch.
         */
        BorrowerSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Sector */
            sector?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** File Count */
            file_count: number;
            /** Analysis Count */
            analysis_count: number;
            /** Latest Decision */
            latest_decision?: ("APPROVE" | "REVIEW" | "DECLINE") | null;
            /** Latest Score */
            latest_score?: number | null;
        };
        /**
         * Factor
         * @description One contribution to the scorecard from finance.score_credit. `points`
         *     can be negative (drag) or positive (boost) — this is the explainability
         *     story: the sum of factor points plus baseline 50 = score.
         */
        Factor: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Points */
            points: number;
        };
        /**
         * FileSummary
         * @description Lightweight file metadata — never carries the raw bytes.
         */
        FileSummary: {
            /** Id */
            id: string;
            /** Filename */
            filename: string;
            /** Page Count */
            page_count: number;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * Flag
         * @description A rule-based red flag from finance.detect_flags.
         */
        Flag: {
            /**
             * Sev
             * @enum {string}
             */
            sev: "high" | "med";
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OversightRequest
         * @description POST /api/analyses/{id}/oversight body. `note` is required for
         *     OVERRIDDEN and ignored for CONFIRMED (endpoint drops it silently).
         */
        OversightRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "CONFIRMED" | "OVERRIDDEN";
            /** Note */
            note?: string | null;
        };
        /**
         * Ratios
         * @description The credit ratios computed by finance.compute_ratios. All optional
         *     because inputs can be missing; the frontend renders '—' for None.
         */
        Ratios: {
            /** Dscr */
            dscr?: number | null;
            /** Debttoebitda */
            debtToEbitda?: number | null;
            /** Debttoequity */
            debtToEquity?: number | null;
            /** Currentratio */
            currentRatio?: number | null;
            /** Quickratio */
            quickRatio?: number | null;
            /** Netmargin */
            netMargin?: number | null;
            /** Revenuegrowth */
            revenueGrowth?: number | null;
            /** Receivablesgrowth */
            receivablesGrowth?: number | null;
            /** Dso */
            dso?: number | null;
            /** Dio */
            dio?: number | null;
            /** Dpo */
            dpo?: number | null;
            /** Ccc */
            ccc?: number | null;
            /** Ocf */
            ocf?: number | null;
            /** Ltv */
            ltv?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
        };
    };
    list_analyses_api_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
                decision?: ("APPROVE" | "REVIEW" | "DECLINE") | null;
                unattached?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_oversight_api_analyses__analysis_id__oversight_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OversightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_borrowers_api_borrowers_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BorrowerSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_borrower_api_borrowers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BorrowerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BorrowerSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_borrower_api_borrowers__borrower_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                borrower_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BorrowerDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_borrower_files_api_borrowers__borrower_id__files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                borrower_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_borrower_api_borrowers__borrower_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                borrower_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BorrowerAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
