/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Analyses */
        get: operations["list_analyses_api_analyses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Company */
            company: string;
            /** Loan Request */
            loan_request?: number | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVE" | "REVIEW" | "DECLINE";
            /** Score */
            score: number;
            /** Financials */
            financials: {
                [key: string]: unknown;
            };
            ratios: components["schemas"]["Ratios"];
            /** Flags */
            flags: components["schemas"]["Flag"][];
            /** Factors */
            factors: components["schemas"]["Factor"][];
            /** Counterfactual */
            counterfactual?: string | null;
            /** Memo */
            memo: string;
        };
        /**
         * AnalysisSummary
         * @description Lightweight row for the history list.
         */
        AnalysisSummary: {
            /** Id */
            id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Company */
            company: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "APPROVE" | "REVIEW" | "DECLINE";
            /** Score */
            score: number;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Text */
            text: string;
        };
        /**
         * Factor
         * @description One contribution to the scorecard from finance.score_credit. `points`
         *     can be negative (drag) or positive (boost) — this is the explainability
         *     story: the sum of factor points plus baseline 50 = score.
         */
        Factor: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
            /** Points */
            points: number;
        };
        /**
         * Flag
         * @description A rule-based red flag from finance.detect_flags.
         */
        Flag: {
            /**
             * Sev
             * @enum {string}
             */
            sev: "high" | "med";
            /** Text */
            text: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Ratios
         * @description The credit ratios computed by finance.compute_ratios. All optional
         *     because inputs can be missing; the frontend renders '—' for None.
         */
        Ratios: {
            /** Dscr */
            dscr?: number | null;
            /** Debttoebitda */
            debtToEbitda?: number | null;
            /** Debttoequity */
            debtToEquity?: number | null;
            /** Currentratio */
            currentRatio?: number | null;
            /** Quickratio */
            quickRatio?: number | null;
            /** Netmargin */
            netMargin?: number | null;
            /** Revenuegrowth */
            revenueGrowth?: number | null;
            /** Receivablesgrowth */
            receivablesGrowth?: number | null;
            /** Dso */
            dso?: number | null;
            /** Dio */
            dio?: number | null;
            /** Dpo */
            dpo?: number | null;
            /** Ccc */
            ccc?: number | null;
            /** Ocf */
            ocf?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_api_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_analyses_api_analyses_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
